### ISSUE TITLE
SSLSocket - virtual

### ISSUE THREAD

**Issue by pavel-pimenov** [airdcpp/airgit#11]
V762 It is possible a virtual function was overridden incorrectly. See third argument of function 'connect' in derived class 'SSLSocket' and base class 'Socket'. sslsocket.h 54

`
class Socket : boost::noncopyable
{
virtual void connect(const AddressInfo& aAddr, const string& aPort, **const string& localPort = Util::emptyString**);

class SSLSocket : public Socket {
virtual void connect(const Socket::AddressInfo& aIp, const string& aPort);

`

**Comment by maksis** [comment]
My plan was to add [`override`](http://en.cppreference.com/w/cpp/language/override) specifiers to avoid problems like that for but unfortunately it's somewhat time consuming to do that with MSVC as it [won't output proper warnings for missing ones like clang does](http://stackoverflow.com/a/29154136) 😞 

It should be done anyway...

**Comment by maksis** [comment]
Seems like this issue is inherited from DC++. Do you know that why is `waitConnected(0)` needed in SSLSocket?

**Comment by maksis** [comment]
This has been fixed
