### ISSUE TITLE
Missing icons for taskbar features

### ISSUE THREAD

**Issue by vBm** [airdcpp/airgit#18]
Even thou both icons are missing tasks work just fine.

![2017-04-30_18-23-56](https://cloud.githubusercontent.com/assets/80596/25566013/3af53b1a-2dd2-11e7-8d40-2a87a4b28c6f.png)

**Comment by Sopor-** [comment]
Is this fixed?

**Comment by vBm** [comment]
ATM I'm on 3.54b and no, it's still not fixed for me.
