### ISSUE TITLE
vld

### ISSUE THREAD

**Issue by pavel-pimenov** [airdcpp/airgit#26]
Visual Leak Detector detected 106 memory leaks (289556 bytes).
Largest number used: 5818861 bytes.
Total allocations: 27264493 bytes.
Visual Leak Detector is now exiting.
The program '[7388] AirDC.exe' has exited with code 0 (0x0).

**Comment by pavel-pimenov** [comment]
V773 Visibility scope of the 'hDC' handle was exited without releasing the resource. A resource leak is possible. atldlgs.h 1917
V773 Visibility scope of the 'pods' pointer was exited without releasing the memory. A memory leak is possible. imagedataobject.cpp 72
V773 Visibility scope of the 'frm' pointer was exited without releasing the memory. A memory leak is possible. textframe.cpp 62
V773 Visibility scope of the 'frm' pointer was exited without releasing the memory. A memory leak is possible. textframe.cpp 72
V773 Visibility scope of the 'frm' pointer was exited without releasing the memory. A memory leak is possible. textframe.cpp 82

**Comment by maksis** [comment]
#34
