### ISSUE TITLE
PVS-Studio analysis report

### ISSUE THREAD

**Issue by pavel-pimenov** [airdcpp/airgit#34]
Online report:
http://www.fly-server.ru/pvs-studio/airdc/

**Comment by pavel-pimenov** [comment]
update http://www.fly-server.ru/pvs-studio/airdc/

**Comment by pavel-pimenov** [comment]
PVS Studio 6.27 
rebuild report http://www.fly-server.ru/pvs-studio/airdc/

**Comment by pavel-pimenov** [comment]
@maksis - try https://www.viva64.com/en/b/0600/

**Comment by pavel-pimenov** [comment]
Date:	03/31/19 10:48:11
PVS-Studio Version:	7.01.31225.1583
Total Warnings (GA):	854
Total Warnings (OP):	312
Total Warnings (64):	121

http://www.fly-server.ru/pvs-studio/airdc/

**Comment by maksis** [comment]
I believe that the important issues from that report have been fixed

**Comment by pavel-pimenov** [comment]
update http://www.fly-server.ru/pvs-studio/airdc/
