### ISSUE TITLE
skiplist

### ISSUE THREAD

**Issue by Lyinggod** [airdcpp/airgit#36]
Apologies but no other contact option appears to be available. AirDCC forum registration appears to be broken. Tried multiple emails but Authentication email not sent and requests to resend indicated email not found. Sorry for posting here but I cannot find an Admin contact for the forum unless logged into forum >:(

**Comment by maksis** [comment]
Thanks for the report. I've done some configuration changes. Could you try if the registration is working now?

**Comment by maksis** [comment]
Seems like it worked
