### ISSUE TITLE
Request: Add a new hublist

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp/airgit#42]
Hello

Is it possible that you insert the xml from my hublist https://dcnf.github.io/Hublist/?

  - xml: https://dcnf.github.io/Hublist/hublist.xml
  - xml.bz2: https://dcnf.github.io/Hublist/hublist.xml.bz2

Thank you in advance.

**Comment by maksis** [comment]
Hublist addresses are generally synced from DC++. Have you requested it to be added there?

**Comment by Kcchouette** [comment]
@maksis not yet

**Comment by Kcchouette** [comment]
I'm closing this issue, duplicate to this (new) one: https://bugs.launchpad.net/airdcpp/+bug/1829064
