### ISSUE TITLE
Error open country_ip_db.mmdb?

### ISSUE THREAD

**Issue by pavel-pimenov** [airdcpp/airgit#50]
[18:37:30] File list refresh finished 
  [18:37:30] Country IP database could not be updated 

https://github.com/airdcpp/airgit/blob/fa33b9f5326c7d170b404acc14492ba79e43869a/airdcpp/airdcpp/GeoManager.cpp#L51

**Comment by maksis** [comment]
Could you post the application version?

**Comment by maksis** [comment]
Seems like the database download links stop after a while when a new database is available. I've updated the download address to point to the latest database file, which should fix the issue soon.
