### ISSUE TITLE
Return value of Wizard*::OnSetActive()

### ISSUE THREAD

**Issue by Caraul** [airdcpp/airgit#8]
Hello,

currently all Return value of Wizard*::OnSetActive() returns 0. From the other side PSN_SETACTIVE is processed as lResult = pT->OnSetActive() ? 0 : -1 and requires "zero to accept the activation, or -1 to activate the next or the previous page". Base implementation simply returns TRUE. I've met problems running hand-built AirDC and solved them replacing 0 with TRUE.
Similar issue is with SetupWizard::OnWizardFinish() - it returns FALSE but is processed as lResult = !pT->OnWizardFinish() inverting value. PSN_WIZFINISH requires "FALSE to allow the wizard to finish" so OnWizardFinish should return TRUE.
I use MS VC 2015 Update 3.

best regards,
Alexander Alexeev

**Comment by maksis** [comment]
Is that a 32 bit debug build? There's a definition (_WTL_NEW_PAGE_NOTIFY_HANDLERS) missing from that configuration which causes those values to be inversed. The 32 bit debug configuration should possibly be removed since only the 64 bit debug config is used for development at the moment.

**Comment by Caraul** [comment]
Oh yeah. I was also surprised by missing version.inc, ssize_t and not included <geoip.h> :) 32-bit really seems slightly outdated, 64-bit is much better. Closing issue, thank you very much.
